@startuml

skinparam classAttributeIconSize 0


together {

class 餐廳

class 服務生

interface 命令{
+ Execute()
}


}

together {

class 廚師{
+ Action()
}

class 點牛排命令{
- cook : 廚師

+ Execute()
}


}

餐廳 ..> 點牛排命令
餐廳 -> 廚師

服務生 o- 命令

點牛排命令 .|>  命令
廚師 <- 點牛排命令 : "cook"

@enduml