@startuml


together {
 class 英雄聯盟
 class 世紀帝國
 class 爆爆王
}

class Computer

interface Game{
+play()
}

class 英雄聯盟{
+play()
}
class 世紀帝國{
+play()
}
class 爆爆王{
+play()
}


Computer .> Game

英雄聯盟 .|> Game
世紀帝國 .|> Game
爆爆王 .|> Game




@enduml