@startuml

skinparam classAttributeIconSize 0


together {

class Client

class invoker

interface Command{
+ Execute()
}




}

together {

class Receiver{
+ Action()
}

class ConcreteCommand{
- receiver : Receiver

+ Execute()
}


}
note right of ConcreteCommand : Execute(): receiver->Action();

Client ..> ConcreteCommand
Client -> Receiver

invoker o- Command

ConcreteCommand .|>  Command
Receiver <- ConcreteCommand : "receiver"

@enduml